[package]
name = "sqlx-example-postgres-listen"
version = "0.1.0"
edition = "2021"
workspace = "../../../"

[dependencies]
sqlx = { path = "../../../", features = [ "runtime-tokio", "postgres" ] }
futures = "0.3.1"
tokio = { workspace = true, optional = true }
